### ISSUE TITLE
Null Pointer Exception in QualarooActivity

### ISSUE THREAD

**Issue by ponsuyambu** [qualaroo/AndroidSDK#13]
Hi 

We get lot of production crashes with the below stack trace.  Could you check what would be the issue?

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.goeuro.rosie/com.qualaroo.QualarooActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.qualaroo.internal.model.Question.a()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity + 3448(ActivityThread.java:3448)
       at android.app.ActivityThread.handleLaunchActivity + 3595(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute + 83(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 135(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute + 95(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage + 2147(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage + 107(Handler.java:107)
       at android.os.Looper.loop + 237(Looper.java:237)
       at android.app.ActivityThread.main + 7811(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 1076(ZygoteInit.java:1076)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'long com.qualaroo.internal.model.Question.a()' on a null object reference
       at com.qualaroo.internal.d.a.a + 10(a.java:10)
       at com.qualaroo.internal.d.a.b + 83(a.java:83)
       at com.qualaroo.internal.d.a.a + 104(a.java:104)
       at com.qualaroo.internal.d.a.b + 83(a.java:83)
       at com.qualaroo.internal.d.a.a + 74(a.java:74)
       at com.qualaroo.internal.d.a.b + 41(a.java:41)
       at com.qualaroo.internal.d.a.<init> + 52(a.java:52)
       at com.qualaroo.ui.h.<init> + 87(h.java:87)
       at com.qualaroo.ui.e.<init> + 36(e.java:36)
       at com.qualaroo.ui.e.<init>(e.java)
       at com.qualaroo.ui.e$a.a + 90(e.java:90)
       at com.qualaroo.Qualaroo.a + 4(Qualaroo.java:4)
       at com.qualaroo.QualarooActivity.onCreate + 47(QualarooActivity.java:47)
       at android.app.Activity.performCreate + 7955(Activity.java:7955)
       at android.app.Activity.performCreate + 7944(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate + 1307(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity + 3423(ActivityThread.java:3423)
       at android.app.ActivityThread.handleLaunchActivity + 3595(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute + 83(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 135(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute + 95(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage + 2147(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage + 107(Handler.java:107)
       at android.os.Looper.loop + 237(Looper.java:237)
       at android.app.ActivityThread.main + 7811(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 1076(ZygoteInit.java:1076)`

**Comment by scana** [comment]
Hi @ponsuyambu would you be able to provide proguard mapping file to marcin@qualaroo.com?
We won't be able to do anything without as whole path is obfuscated.

**Comment by ponsuyambu** [comment]
Hi,

it's the Deobfuscated log. Qualaroo SDK itself comes with the obfuscated jar. See the attached pic.

![Screenshot 2020-02-13 at 17 11 52](https://user-images.githubusercontent.com/4482905/74454641-7abbd080-4e84-11ea-92fe-d0a03b8ca047.png)

**Comment by ponsuyambu** [comment]
@scana any update on this ticket? our crashes on increasing day by day, please help

**Comment by ahabbaba9** [comment]
@scana is there an update on this? I've just gotten Qualaroo set up and am seeing a similar crash (in `Message`, instead of `Question`)
I am using version 1.9.0

**Comment by scana** [comment]
@ahabbaba9 I am sorry, I am no longer employed at Qualaroo. From what I can see in this stacktrace, this seems like a backend issue. The only solution that comes to mind is to fork the library and work your way around with additional null-checks. However, this won't be a long-lasting solution.

I reached out to the new owners of Qualaroo and offered my help on fixing this and the other issues present, but I haven't got any response from them - so my hands are tied here.

**Comment by ahabbaba9** [comment]
@scana thank you for the reply! Appreciate your help on this

**Comment by ahabbaba9** [comment]
@gorillka @radiantnode pinging you both, since you show up as contributors on the main landing page. Maybe you can help give some insight here?

**Comment by durgeshqualaroo** [comment]
@ponsuyambu @ahabbaba9 We sincerely sorry for the inconvenience. Please connect with us at mobile@qualaroo.com. We need a few information regrading the survey that we cannot request here. Rest assured a dedicated mobile team is maintaining the repository and promising to act fast on it. Thank you for your kind patience.

**Comment by ponsuyambu** [comment]
@durgeshqualaroo I have sent an email.

**Comment by ahabbaba9** [comment]
Looks like this issue is fixed in the version 2.0.0! Thank you!

**Comment by ponsuyambu** [comment]
@ahabbaba9 Where did you find the version 2.0.0? I still see the latest version as 1.9.0. https://github.com/qualaroo/android-sdk/releases

**Comment by durgeshqualaroo** [comment]
@ponsuyambu I saw your email and I am responding you back with the steps. The upgraded version is something we're evaluating with the various circumstances. Once approved, it will be available here for everyone. Thank you for your kind patience.

**Comment by durgeshqualaroo** [comment]
@ahabbaba9 Thanks for the confirmation.

**Comment by ponsuyambu** [comment]
This issue was fixed in Qualaroo Backend and it is working fine for me now. The issue was related to handling non-English languages in their backend. Thanks for the support @durgeshqualaroo
